

/**
- Complex(float re,im)
- Matrice( Complex **v)
- Matrice_oarecare (int lin, int col) : Matrice
- Matrice_patratica (int dim): Matrice

TO DO:
-PARAMETRIZARE CONSTR DESTR
-COPIERE FUNCTII IMPORTANTE IN BAZA
-MATRICE TRIUNGHIULARA SI DIAGONALA         ***
-MODIFICAT RETURNARILE SUPRAINCARCARII OPERATORILOR
-STABILIT VALOARE DE EROARE PENTRU RETUNARI
*/


/**
1.PRELUCRARE N ELEMENTE
    1.1. CITIRE ELEMENTE
    1.2. AFISARE NUMAR MATRICI MEMORATE
    1.3. AFISARE
2. MATRICE OARECARE
    2.1. ADUNARE 2 MATRICI
        2.1.1. INTRODUCERE 2
        2.1.2. ADUNARE 2 DIN CELE N
3. MATRICE PATRATICA




 */
